### ISSUE TITLE
final night fixes & additions

### ISSUE THREAD

**Issue by sinker** [OpenNews/opennews-website#12]
* [x] fix links in footer
* [x] fellowships sidebar addition
* [x] surface corresponding page for same
* [x] reorganize the directories to match the projects 
* [x] fix fucking links corresponding to those
* [x] potentially reorg the who we are page to include history & sponsors
* [x] links in announcement blog
* [x] put in the SRCCON blog post
* [x] fix videos using the SRCCON.org embed code
* [x] make a valient attenmpt at fixing the fucking responsive weirdness

**Comment by sinker** [comment]
probably that resurfaced fellowship community page should be looked at and reworked to (a) reduce the "Knight-Mozilla" references and (b) make sense in terms of a hiatus program a little more. I tried, but another set of eyes would be good before we lock down the site.

**Comment by sinker** [comment]
there are placeholder images in the two blog post still

**Comment by erikao** [comment]
tracking text updates/questions here https://public.etherpad-mozilla.org/p/opennews-2017-announcement-site-updates-launch

**Comment by sinker** [comment]
CLOSING.
